coverage:
  all_nodes: 0
  covered_nodes: 0
mutation_score: 100.0
mutations:
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\pynguin\\\
    tests\\test_093.py\", line 35, in test_case_1\n    assert var_2 == 2\nAssertionError\n"
  killer: test_case_1 (datasets.pynguin.tests.test_093.TestAll)
  module: &id001 !!python/module:datasets.pynguin.programs.program_093 ''
  mutations:
  - lineno: 5
    operator: ASR
  number: 1
  status: killed
  tests_run: 2
  time: 0.010716676712036133
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\pynguin\\\
    tests\\test_093.py\", line 9, in test_case_0\n    assert var_0 == 0\nAssertionError\n"
  killer: test_case_0 (datasets.pynguin.tests.test_093.TestAll)
  module: *id001
  mutations:
  - lineno: 4
    operator: COI
  number: 2
  status: killed
  tests_run: 1
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\pynguin\\\
    tests\\test_093.py\", line 9, in test_case_0\n    assert var_0 == 0\nAssertionError\n"
  killer: test_case_0 (datasets.pynguin.tests.test_093.TestAll)
  module: *id001
  mutations:
  - lineno: 4
    operator: ROR
  number: 3
  status: killed
  tests_run: 1
  time: 0.0
number_of_tests: 2
targets:
- datasets.pynguin.programs.program_093
tests:
- name: datasets.pynguin.tests.test_093
  target: null
  time: 0.0
time_stats:
  create_mutant_module: 0.0
  create_target_ast: 0.0010063648223876953
  mutate_module: 0.03685331344604492
  run_tests_with_mutant: 0.011710643768310547
total_time: 0.04292607307434082
