coverage:
  all_nodes: 0
  covered_nodes: 0
mutation_score: 100.0
mutations:
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\pynguin\\\
    tests\\test_050.py\", line 10, in test_case_0\n    assert var_0 == 'Yt-'\nAssertionError\n"
  killer: test_case_0 (datasets.pynguin.tests.test_050.TestAll)
  module: !!python/module:datasets.pynguin.programs.program_050 ''
  mutations:
  - lineno: 3
    operator: LCR
  number: 1
  status: killed
  tests_run: 1
  time: 0.0009999275207519531
number_of_tests: 1
targets:
- datasets.pynguin.programs.program_050
tests:
- name: datasets.pynguin.tests.test_050
  target: null
  time: 0.0
time_stats:
  create_mutant_module: 0.0
  create_target_ast: 0.0
  mutate_module: 0.01900029182434082
  run_tests_with_mutant: 0.0009999275207519531
total_time: 0.025002479553222656
