coverage:
  all_nodes: 0
  covered_nodes: 0
mutation_score: 100.0
mutations:
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot1\\tests\\test_034.py\", line 9, in test_2\n    self.assertEqual(centered_hexagonal_number(2),\
    \ 7)\nAssertionError: 2.5 != 7\n"
  killer: test_2 (datasets.GPT_4.Zero_shot1.tests.test_034.TestVersion)
  module: &id001 !!python/module:datasets.GPT_4.Zero_shot1.programs.program_034 ''
  mutations:
  - lineno: 2
    operator: AOR
  number: 1
  status: killed
  tests_run: 2
  time: 0.0009987354278564453
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot1\\tests\\test_034.py\", line 9, in test_2\n    self.assertEqual(centered_hexagonal_number(2),\
    \ 7)\nAssertionError: 2 != 7\n"
  killer: test_2 (datasets.GPT_4.Zero_shot1.tests.test_034.TestVersion)
  module: *id001
  mutations:
  - lineno: 2
    operator: AOR
  number: 2
  status: killed
  tests_run: 2
  time: 0.0009980201721191406
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot1\\tests\\test_034.py\", line 9, in test_2\n    self.assertEqual(centered_hexagonal_number(2),\
    \ 7)\nAssertionError: 10 != 7\n"
  killer: test_2 (datasets.GPT_4.Zero_shot1.tests.test_034.TestVersion)
  module: *id001
  mutations:
  - lineno: 2
    operator: AOR
  number: 3
  status: killed
  tests_run: 2
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot1\\tests\\test_034.py\", line 6, in test_1\n    self.assertEqual(centered_hexagonal_number(1),\
    \ 1)\n  File \"datasets.GPT_4.Zero_shot1.programs.program_034\", line 2, in centered_hexagonal_number\n\
    ZeroDivisionError: division by zero\n"
  killer: test_1 (datasets.GPT_4.Zero_shot1.tests.test_034.TestVersion)
  module: *id001
  mutations:
  - lineno: 2
    operator: AOR
  number: 4
  status: killed
  tests_run: 1
  time: 0.0009982585906982422
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot1\\tests\\test_034.py\", line 6, in test_1\n    self.assertEqual(centered_hexagonal_number(1),\
    \ 1)\n  File \"datasets.GPT_4.Zero_shot1.programs.program_034\", line 2, in centered_hexagonal_number\n\
    ZeroDivisionError: integer division or modulo by zero\n"
  killer: test_1 (datasets.GPT_4.Zero_shot1.tests.test_034.TestVersion)
  module: *id001
  mutations:
  - lineno: 2
    operator: AOR
  number: 5
  status: killed
  tests_run: 1
  time: 0.0010006427764892578
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot1\\tests\\test_034.py\", line 6, in test_1\n    self.assertEqual(centered_hexagonal_number(1),\
    \ 1)\nAssertionError: 2 != 1\n"
  killer: test_1 (datasets.GPT_4.Zero_shot1.tests.test_034.TestVersion)
  module: *id001
  mutations:
  - lineno: 2
    operator: AOR
  number: 6
  status: killed
  tests_run: 1
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot1\\tests\\test_034.py\", line 6, in test_1\n    self.assertEqual(centered_hexagonal_number(1),\
    \ 1)\nAssertionError: 7 != 1\n"
  killer: test_1 (datasets.GPT_4.Zero_shot1.tests.test_034.TestVersion)
  module: *id001
  mutations:
  - lineno: 2
    operator: AOR
  number: 7
  status: killed
  tests_run: 1
  time: 0.0009987354278564453
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot1\\tests\\test_034.py\", line 6, in test_1\n    self.assertEqual(centered_hexagonal_number(1),\
    \ 1)\nAssertionError: -1 != 1\n"
  killer: test_1 (datasets.GPT_4.Zero_shot1.tests.test_034.TestVersion)
  module: *id001
  mutations:
  - lineno: 2
    operator: AOR
  number: 8
  status: killed
  tests_run: 1
  time: 0.0009996891021728516
number_of_tests: 8
targets:
- datasets.GPT_4.Zero_shot1.programs.program_034
tests:
- name: datasets.GPT_4.Zero_shot1.tests.test_034
  target: null
  time: 0.0
time_stats:
  create_mutant_module: 0.0
  create_target_ast: 0.0
  mutate_module: 0.034512996673583984
  run_tests_with_mutant: 0.005994081497192383
total_time: 0.04044365882873535
