coverage:
  all_nodes: 0
  covered_nodes: 0
mutation_score: 100.0
mutations:
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot1\\tests\\test_037.py\", line 6, in test_1\n    self.assertEqual(closest_num(0),\
    \ -1)\nAssertionError: 1 != -1\n"
  killer: test_1 (datasets.GPT_4.Zero_shot1.tests.test_037.TestVersion)
  module: !!python/module:datasets.GPT_4.Zero_shot1.programs.program_037 ''
  mutations:
  - lineno: 2
    operator: AOR
  number: 1
  status: killed
  tests_run: 1
  time: 0.0009930133819580078
number_of_tests: 9
targets:
- datasets.GPT_4.Zero_shot1.programs.program_037
tests:
- name: datasets.GPT_4.Zero_shot1.tests.test_037
  target: null
  time: 0.0
time_stats:
  create_mutant_module: 0.0
  create_target_ast: 0.0009930133819580078
  mutate_module: 0.01450967788696289
  run_tests_with_mutant: 0.0009930133819580078
total_time: 0.020534515380859375
