coverage:
  all_nodes: 0
  covered_nodes: 0
mutation_score: 100.0
mutations:
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot1\\tests\\test_030.py\", line 6, in test_1\n    self.assertAlmostEqual(volume_sphere(1),\
    \ (4/3) * math.pi)\nAssertionError: 3.141592653589793 != 4.1887902047863905 within\
    \ 7 places (1.0471975511965974 difference)\n"
  killer: test_1 (datasets.GPT_4.Zero_shot1.tests.test_030.TestVersion)
  module: &id001 !!python/module:datasets.GPT_4.Zero_shot1.programs.program_030 ''
  mutations:
  - lineno: 3
    operator: AOR
  number: 1
  status: killed
  tests_run: 1
  time: 0.0010013580322265625
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot1\\tests\\test_030.py\", line 6, in test_1\n    self.assertAlmostEqual(volume_sphere(1),\
    \ (4/3) * math.pi)\nAssertionError: 37.69911184307752 != 4.1887902047863905 within\
    \ 7 places (33.510321638291124 difference)\n"
  killer: test_1 (datasets.GPT_4.Zero_shot1.tests.test_030.TestVersion)
  module: *id001
  mutations:
  - lineno: 3
    operator: AOR
  number: 2
  status: killed
  tests_run: 1
  time: 0.0009996891021728516
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot1\\tests\\test_030.py\", line 6, in test_1\n    self.assertAlmostEqual(volume_sphere(1),\
    \ (4/3) * math.pi)\nAssertionError: 0.42441318157838753 != 4.1887902047863905\
    \ within 7 places (3.764377023208003 difference)\n"
  killer: test_1 (datasets.GPT_4.Zero_shot1.tests.test_030.TestVersion)
  module: *id001
  mutations:
  - lineno: 3
    operator: AOR
  number: 3
  status: killed
  tests_run: 1
  time: 0.0009996891021728516
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot1\\tests\\test_030.py\", line 6, in test_1\n    self.assertAlmostEqual(volume_sphere(1),\
    \ (4/3) * math.pi)\nAssertionError: 0.0 != 4.1887902047863905 within 7 places\
    \ (4.1887902047863905 difference)\n"
  killer: test_1 (datasets.GPT_4.Zero_shot1.tests.test_030.TestVersion)
  module: *id001
  mutations:
  - lineno: 3
    operator: AOR
  number: 4
  status: killed
  tests_run: 1
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot1\\tests\\test_030.py\", line 6, in test_1\n    self.assertAlmostEqual(volume_sphere(1),\
    \ (4/3) * math.pi)\nAssertionError: 2.4689177219977116 != 4.1887902047863905 within\
    \ 7 places (1.7198724827886789 difference)\n"
  killer: test_1 (datasets.GPT_4.Zero_shot1.tests.test_030.TestVersion)
  module: *id001
  mutations:
  - lineno: 3
    operator: AOR
  number: 5
  status: killed
  tests_run: 1
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot1\\tests\\test_030.py\", line 9, in test_2\n    self.assertAlmostEqual(volume_sphere(2),\
    \ (4/3) * math.pi * 8)\nAssertionError: 8.377580409572781 != 33.510321638291124\
    \ within 7 places (25.132741228718345 difference)\n"
  killer: test_2 (datasets.GPT_4.Zero_shot1.tests.test_030.TestVersion)
  module: *id001
  mutations:
  - lineno: 3
    operator: AOR
  number: 6
  status: killed
  tests_run: 2
  time: 0.0010004043579101562
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot1\\tests\\test_030.py\", line 6, in test_1\n    self.assertAlmostEqual(volume_sphere(1),\
    \ (4/3) * math.pi)\nAssertionError: 4.0 != 4.1887902047863905 within 7 places\
    \ (0.18879020478639053 difference)\n"
  killer: test_1 (datasets.GPT_4.Zero_shot1.tests.test_030.TestVersion)
  module: *id001
  mutations:
  - lineno: 3
    operator: AOR
  number: 7
  status: killed
  tests_run: 1
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot1\\tests\\test_030.py\", line 9, in test_2\n    self.assertAlmostEqual(volume_sphere(2),\
    \ (4/3) * math.pi * 8)\nAssertionError: 70.18385351885765 != 33.510321638291124\
    \ within 7 places (36.67353188056652 difference)\n"
  killer: test_2 (datasets.GPT_4.Zero_shot1.tests.test_030.TestVersion)
  module: *id001
  mutations:
  - lineno: 3
    operator: AOR
  number: 8
  status: killed
  tests_run: 2
  time: 0.00099945068359375
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot1\\tests\\test_030.py\", line 9, in test_2\n    self.assertAlmostEqual(volume_sphere(2),\
    \ (4/3) * math.pi * 8)\nAssertionError: 8.377580409572781 != 33.510321638291124\
    \ within 7 places (25.132741228718345 difference)\n"
  killer: test_2 (datasets.GPT_4.Zero_shot1.tests.test_030.TestVersion)
  module: *id001
  mutations:
  - lineno: 3
    operator: AOR
  number: 9
  status: killed
  tests_run: 2
  time: 0.0010020732879638672
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot1\\tests\\test_030.py\", line 6, in test_1\n    self.assertAlmostEqual(volume_sphere(1),\
    \ (4/3) * math.pi)\nAssertionError: 4.0 != 4.1887902047863905 within 7 places\
    \ (0.18879020478639053 difference)\n"
  killer: test_1 (datasets.GPT_4.Zero_shot1.tests.test_030.TestVersion)
  module: *id001
  mutations:
  - lineno: 3
    operator: AOR
  number: 10
  status: killed
  tests_run: 1
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot1\\tests\\test_030.py\", line 9, in test_2\n    self.assertAlmostEqual(volume_sphere(2),\
    \ (4/3) * math.pi * 8)\nAssertionError: 140.3677070377153 != 33.510321638291124\
    \ within 7 places (106.85738539942417 difference)\n"
  killer: test_2 (datasets.GPT_4.Zero_shot1.tests.test_030.TestVersion)
  module: *id001
  mutations:
  - lineno: 3
    operator: AOR
  number: 11
  status: killed
  tests_run: 2
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot1\\tests\\test_030.py\", line 9, in test_2\n    self.assertAlmostEqual(volume_sphere(2),\
    \ (4/3) * math.pi * 8)\nAssertionError: 8.377580409572781 != 33.510321638291124\
    \ within 7 places (25.132741228718345 difference)\n"
  killer: test_2 (datasets.GPT_4.Zero_shot1.tests.test_030.TestVersion)
  module: *id001
  mutations:
  - lineno: 3
    operator: AOR
  number: 12
  status: killed
  tests_run: 2
  time: 0.0009992122650146484
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot1\\tests\\test_030.py\", line 6, in test_1\n    self.assertAlmostEqual(volume_sphere(1),\
    \ (4/3) * math.pi)\nAssertionError: 4.0 != 4.1887902047863905 within 7 places\
    \ (0.18879020478639053 difference)\n"
  killer: test_1 (datasets.GPT_4.Zero_shot1.tests.test_030.TestVersion)
  module: *id001
  mutations:
  - lineno: 3
    operator: AOR
  number: 13
  status: killed
  tests_run: 1
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot1\\tests\\test_030.py\", line 9, in test_2\n    self.assertAlmostEqual(volume_sphere(2),\
    \ (4/3) * math.pi * 8)\nAssertionError: 280.7354140754306 != 33.510321638291124\
    \ within 7 places (247.22509243713947 difference)\n"
  killer: test_2 (datasets.GPT_4.Zero_shot1.tests.test_030.TestVersion)
  module: *id001
  mutations:
  - lineno: 3
    operator: AOR
  number: 14
  status: killed
  tests_run: 2
  time: 0.0
number_of_tests: 7
targets:
- datasets.GPT_4.Zero_shot1.programs.program_030
tests:
- name: datasets.GPT_4.Zero_shot1.tests.test_030
  target: null
  time: 0.0
time_stats:
  create_mutant_module: 0.0
  create_target_ast: 0.0
  mutate_module: 0.05150914192199707
  run_tests_with_mutant: 0.009002447128295898
total_time: 0.05749773979187012
