[*] Start mutation process:
   - targets: datasets.o3.programs.program_056
   - tests: datasets.o3.tests.test_056
[*] 6 tests passed:
   - datasets.o3.tests.test_056 [0.00000 s]
[*] Start mutants generation and execution:
   - [#   1] AOR datasets.o3.programs.program_056: [0.00000 s] killed by test_all_ones (datasets.o3.tests.test_056.TestVersion)

Traceback (most recent call last):
  File "C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.\datasets\o3\tests\test_056.py", line 15, in test_all_ones
    self.assertEqual(odd_Equivalent("1111", 4), 4)
AssertionError: -4 != 4

   - [#   2] COI datasets.o3.programs.program_056: [0.00000 s] killed by test_all_ones (datasets.o3.tests.test_056.TestVersion)

Traceback (most recent call last):
  File "C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.\datasets\o3\tests\test_056.py", line 15, in test_all_ones
    self.assertEqual(odd_Equivalent("1111", 4), 4)
AssertionError: 0 != 4

   - [#   3] ROR datasets.o3.programs.program_056: [0.00000 s] killed by test_all_ones (datasets.o3.tests.test_056.TestVersion)

Traceback (most recent call last):
  File "C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.\datasets\o3\tests\test_056.py", line 15, in test_all_ones
    self.assertEqual(odd_Equivalent("1111", 4), 4)
AssertionError: 0 != 4

[*] Mutation score [0.03125 s]: 100.0%
   - all: 3
   - killed: 3 (100.0%)
   - survived: 0 (0.0%)
   - incompetent: 0 (0.0%)
   - timeout: 0 (0.0%)
HI SANDER, RUNNING MUTPY FROM: C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.venv38\lib\site-packages\mutpy\commandline.py
