coverage:
  all_nodes: 0
  covered_nodes: 0
mutation_score: 100.0
mutations:
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot2\\tests\\test_030.py\", line 9, in test_sphere_2\n    self.assertAlmostEqual(volume_sphere(1),\
    \ (4/3)*math.pi)\nAssertionError: 3.141592653589793 != 4.1887902047863905 within\
    \ 7 places (1.0471975511965974 difference)\n"
  killer: test_sphere_2 (datasets.GPT_4.Zero_shot2.tests.test_030.TestVersion)
  module: &id001 !!python/module:datasets.GPT_4.Zero_shot2.programs.program_030 ''
  mutations:
  - lineno: 3
    operator: AOR
  number: 1
  status: killed
  tests_run: 2
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot2\\tests\\test_030.py\", line 9, in test_sphere_2\n    self.assertAlmostEqual(volume_sphere(1),\
    \ (4/3)*math.pi)\nAssertionError: 37.69911184307752 != 4.1887902047863905 within\
    \ 7 places (33.510321638291124 difference)\n"
  killer: test_sphere_2 (datasets.GPT_4.Zero_shot2.tests.test_030.TestVersion)
  module: *id001
  mutations:
  - lineno: 3
    operator: AOR
  number: 2
  status: killed
  tests_run: 2
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot2\\tests\\test_030.py\", line 9, in test_sphere_2\n    self.assertAlmostEqual(volume_sphere(1),\
    \ (4/3)*math.pi)\nAssertionError: 0.42441318157838753 != 4.1887902047863905 within\
    \ 7 places (3.764377023208003 difference)\n"
  killer: test_sphere_2 (datasets.GPT_4.Zero_shot2.tests.test_030.TestVersion)
  module: *id001
  mutations:
  - lineno: 3
    operator: AOR
  number: 3
  status: killed
  tests_run: 2
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot2\\tests\\test_030.py\", line 9, in test_sphere_2\n    self.assertAlmostEqual(volume_sphere(1),\
    \ (4/3)*math.pi)\nAssertionError: 0.0 != 4.1887902047863905 within 7 places (4.1887902047863905\
    \ difference)\n"
  killer: test_sphere_2 (datasets.GPT_4.Zero_shot2.tests.test_030.TestVersion)
  module: *id001
  mutations:
  - lineno: 3
    operator: AOR
  number: 4
  status: killed
  tests_run: 2
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot2\\tests\\test_030.py\", line 9, in test_sphere_2\n    self.assertAlmostEqual(volume_sphere(1),\
    \ (4/3)*math.pi)\nAssertionError: 2.4689177219977116 != 4.1887902047863905 within\
    \ 7 places (1.7198724827886789 difference)\n"
  killer: test_sphere_2 (datasets.GPT_4.Zero_shot2.tests.test_030.TestVersion)
  module: *id001
  mutations:
  - lineno: 3
    operator: AOR
  number: 5
  status: killed
  tests_run: 2
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot2\\tests\\test_030.py\", line 6, in test_sphere_1\n    self.assertEqual(volume_sphere(0),\
    \ 0.0)\n  File \"datasets.GPT_4.Zero_shot2.programs.program_030\", line 3, in\
    \ volume_sphere\nZeroDivisionError: float division by zero\n"
  killer: test_sphere_1 (datasets.GPT_4.Zero_shot2.tests.test_030.TestVersion)
  module: *id001
  mutations:
  - lineno: 3
    operator: AOR
  number: 6
  status: killed
  tests_run: 1
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot2\\tests\\test_030.py\", line 6, in test_sphere_1\n    self.assertEqual(volume_sphere(0),\
    \ 0.0)\n  File \"datasets.GPT_4.Zero_shot2.programs.program_030\", line 3, in\
    \ volume_sphere\nZeroDivisionError: float divmod()\n"
  killer: test_sphere_1 (datasets.GPT_4.Zero_shot2.tests.test_030.TestVersion)
  module: *id001
  mutations:
  - lineno: 3
    operator: AOR
  number: 7
  status: killed
  tests_run: 1
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot2\\tests\\test_030.py\", line 12, in test_sphere_3\n    self.assertAlmostEqual(volume_sphere(2),\
    \ (4/3)*math.pi*8)\nAssertionError: 70.18385351885765 != 33.510321638291124 within\
    \ 7 places (36.67353188056652 difference)\n"
  killer: test_sphere_3 (datasets.GPT_4.Zero_shot2.tests.test_030.TestVersion)
  module: *id001
  mutations:
  - lineno: 3
    operator: AOR
  number: 8
  status: killed
  tests_run: 3
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot2\\tests\\test_030.py\", line 6, in test_sphere_1\n    self.assertEqual(volume_sphere(0),\
    \ 0.0)\n  File \"datasets.GPT_4.Zero_shot2.programs.program_030\", line 3, in\
    \ volume_sphere\nZeroDivisionError: float division by zero\n"
  killer: test_sphere_1 (datasets.GPT_4.Zero_shot2.tests.test_030.TestVersion)
  module: *id001
  mutations:
  - lineno: 3
    operator: AOR
  number: 9
  status: killed
  tests_run: 1
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot2\\tests\\test_030.py\", line 6, in test_sphere_1\n    self.assertEqual(volume_sphere(0),\
    \ 0.0)\n  File \"datasets.GPT_4.Zero_shot2.programs.program_030\", line 3, in\
    \ volume_sphere\nZeroDivisionError: float divmod()\n"
  killer: test_sphere_1 (datasets.GPT_4.Zero_shot2.tests.test_030.TestVersion)
  module: *id001
  mutations:
  - lineno: 3
    operator: AOR
  number: 10
  status: killed
  tests_run: 1
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot2\\tests\\test_030.py\", line 12, in test_sphere_3\n    self.assertAlmostEqual(volume_sphere(2),\
    \ (4/3)*math.pi*8)\nAssertionError: 140.3677070377153 != 33.510321638291124 within\
    \ 7 places (106.85738539942417 difference)\n"
  killer: test_sphere_3 (datasets.GPT_4.Zero_shot2.tests.test_030.TestVersion)
  module: *id001
  mutations:
  - lineno: 3
    operator: AOR
  number: 11
  status: killed
  tests_run: 3
  time: 0.01351785659790039
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot2\\tests\\test_030.py\", line 6, in test_sphere_1\n    self.assertEqual(volume_sphere(0),\
    \ 0.0)\n  File \"datasets.GPT_4.Zero_shot2.programs.program_030\", line 3, in\
    \ volume_sphere\nZeroDivisionError: float division by zero\n"
  killer: test_sphere_1 (datasets.GPT_4.Zero_shot2.tests.test_030.TestVersion)
  module: *id001
  mutations:
  - lineno: 3
    operator: AOR
  number: 12
  status: killed
  tests_run: 1
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot2\\tests\\test_030.py\", line 6, in test_sphere_1\n    self.assertEqual(volume_sphere(0),\
    \ 0.0)\n  File \"datasets.GPT_4.Zero_shot2.programs.program_030\", line 3, in\
    \ volume_sphere\nZeroDivisionError: float divmod()\n"
  killer: test_sphere_1 (datasets.GPT_4.Zero_shot2.tests.test_030.TestVersion)
  module: *id001
  mutations:
  - lineno: 3
    operator: AOR
  number: 13
  status: killed
  tests_run: 1
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Zero_shot2\\tests\\test_030.py\", line 6, in test_sphere_1\n    self.assertEqual(volume_sphere(0),\
    \ 0.0)\nAssertionError: 1.0 != 0.0\n"
  killer: test_sphere_1 (datasets.GPT_4.Zero_shot2.tests.test_030.TestVersion)
  module: *id001
  mutations:
  - lineno: 3
    operator: AOR
  number: 14
  status: killed
  tests_run: 1
  time: 0.0
number_of_tests: 7
targets:
- datasets.GPT_4.Zero_shot2.programs.program_030
tests:
- name: datasets.GPT_4.Zero_shot2.tests.test_030
  target: null
  time: 0.0
time_stats:
  create_mutant_module: 0.0
  create_target_ast: 0.0
  mutate_module: 0.06336140632629395
  run_tests_with_mutant: 0.01351785659790039
total_time: 0.07898426055908203
