coverage:
  all_nodes: 0
  covered_nodes: 0
mutation_score: 100.0
mutations:
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Few_shot\\tests\\test_033.py\", line 6, in test_case_1\n    self.assertEqual(surfacearea_sphere(1),\
    \ 4 * math.pi) # Unit sphere)\nAssertionError: 1.2732395447351628 != 12.566370614359172\n"
  killer: test_case_1 (datasets.GPT_4.Few_shot.tests.test_033.TestVersion)
  module: &id001 !!python/module:datasets.GPT_4.Few_shot.programs.program_033 ''
  mutations:
  - lineno: 3
    operator: AOR
  number: 1
  status: killed
  tests_run: 1
  time: 0.0009999275207519531
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Few_shot\\tests\\test_033.py\", line 6, in test_case_1\n    self.assertEqual(surfacearea_sphere(1),\
    \ 4 * math.pi) # Unit sphere)\nAssertionError: 1.0 != 12.566370614359172\n"
  killer: test_case_1 (datasets.GPT_4.Few_shot.tests.test_033.TestVersion)
  module: *id001
  mutations:
  - lineno: 3
    operator: AOR
  number: 2
  status: killed
  tests_run: 1
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Few_shot\\tests\\test_033.py\", line 6, in test_case_1\n    self.assertEqual(surfacearea_sphere(1),\
    \ 4 * math.pi) # Unit sphere)\nAssertionError: 77.8802336483881 != 12.566370614359172\n"
  killer: test_case_1 (datasets.GPT_4.Few_shot.tests.test_033.TestVersion)
  module: *id001
  mutations:
  - lineno: 3
    operator: AOR
  number: 3
  status: killed
  tests_run: 1
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Few_shot\\tests\\test_033.py\", line 9, in test_case_2\n    self.assertEqual(surfacearea_sphere(0),\
    \ 0) # Zero radius)\n  File \"datasets.GPT_4.Few_shot.programs.program_033\",\
    \ line 3, in surfacearea_sphere\nZeroDivisionError: float division by zero\n"
  killer: test_case_2 (datasets.GPT_4.Few_shot.tests.test_033.TestVersion)
  module: *id001
  mutations:
  - lineno: 3
    operator: AOR
  number: 4
  status: killed
  tests_run: 2
  time: 0.0009996891021728516
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Few_shot\\tests\\test_033.py\", line 6, in test_case_1\n    self.assertEqual(surfacearea_sphere(1),\
    \ 4 * math.pi) # Unit sphere)\nAssertionError: 12.0 != 12.566370614359172\n"
  killer: test_case_1 (datasets.GPT_4.Few_shot.tests.test_033.TestVersion)
  module: *id001
  mutations:
  - lineno: 3
    operator: AOR
  number: 5
  status: killed
  tests_run: 1
  time: 0.0009992122650146484
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Few_shot\\tests\\test_033.py\", line 12, in test_case_3\n    self.assertEqual(surfacearea_sphere(3),\
    \ 4 * math.pi * (3**2) )  # Normal positive radius)\nAssertionError: 5953.2051226175645\
    \ != 113.09733552923255\n"
  killer: test_case_3 (datasets.GPT_4.Few_shot.tests.test_033.TestVersion)
  module: *id001
  mutations:
  - lineno: 3
    operator: AOR
  number: 6
  status: killed
  tests_run: 3
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Few_shot\\tests\\test_033.py\", line 9, in test_case_2\n    self.assertEqual(surfacearea_sphere(0),\
    \ 0) # Zero radius)\n  File \"datasets.GPT_4.Few_shot.programs.program_033\",\
    \ line 3, in surfacearea_sphere\nZeroDivisionError: float division by zero\n"
  killer: test_case_2 (datasets.GPT_4.Few_shot.tests.test_033.TestVersion)
  module: *id001
  mutations:
  - lineno: 3
    operator: AOR
  number: 7
  status: killed
  tests_run: 2
  time: 0.001001596450805664
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Few_shot\\tests\\test_033.py\", line 6, in test_case_1\n    self.assertEqual(surfacearea_sphere(1),\
    \ 4 * math.pi) # Unit sphere)\nAssertionError: 12.0 != 12.566370614359172\n"
  killer: test_case_1 (datasets.GPT_4.Few_shot.tests.test_033.TestVersion)
  module: *id001
  mutations:
  - lineno: 3
    operator: AOR
  number: 8
  status: killed
  tests_run: 1
  time: 0.0010013580322265625
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Few_shot\\tests\\test_033.py\", line 9, in test_case_2\n    self.assertEqual(surfacearea_sphere(0),\
    \ 0) # Zero radius)\nAssertionError: 1.0 != 0\n"
  killer: test_case_2 (datasets.GPT_4.Few_shot.tests.test_033.TestVersion)
  module: *id001
  mutations:
  - lineno: 3
    operator: AOR
  number: 9
  status: killed
  tests_run: 2
  time: 0.00099945068359375
number_of_tests: 8
targets:
- datasets.GPT_4.Few_shot.programs.program_033
tests:
- name: datasets.GPT_4.Few_shot.tests.test_033
  target: null
  time: 0.0
time_stats:
  create_mutant_module: 0.0009603500366210938
  create_target_ast: 0.0009999275207519531
  mutate_module: 0.04451179504394531
  run_tests_with_mutant: 0.010000228881835938
total_time: 0.05050373077392578
