[*] Start mutation process:
   - targets: datasets.GPT_4.Zero_shot2.programs.program_033
   - tests: datasets.GPT_4.Zero_shot2.tests.test_033
[*] 7 tests passed:
   - datasets.GPT_4.Zero_shot2.tests.test_033 [0.00000 s]
[*] Start mutants generation and execution:
   - [#   1] AOR datasets.GPT_4.Zero_shot2.programs.program_033: [0.00000 s] killed by test_area_2 (datasets.GPT_4.Zero_shot2.tests.test_033.TestVersion)

Traceback (most recent call last):
  File "C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.\datasets\GPT_4\Zero_shot2\tests\test_033.py", line 9, in test_area_2
    self.assertAlmostEqual(surfacearea_sphere(1), 4 * math.pi)
AssertionError: 1.2732395447351628 != 12.566370614359172 within 7 places (11.29313106962401 difference)

   - [#   2] AOR datasets.GPT_4.Zero_shot2.programs.program_033: [0.00000 s] killed by test_area_2 (datasets.GPT_4.Zero_shot2.tests.test_033.TestVersion)

Traceback (most recent call last):
  File "C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.\datasets\GPT_4\Zero_shot2\tests\test_033.py", line 9, in test_area_2
    self.assertAlmostEqual(surfacearea_sphere(1), 4 * math.pi)
AssertionError: 1.0 != 12.566370614359172 within 7 places (11.566370614359172 difference)

   - [#   3] AOR datasets.GPT_4.Zero_shot2.programs.program_033: [0.00000 s] killed by test_area_2 (datasets.GPT_4.Zero_shot2.tests.test_033.TestVersion)

Traceback (most recent call last):
  File "C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.\datasets\GPT_4\Zero_shot2\tests\test_033.py", line 9, in test_area_2
    self.assertAlmostEqual(surfacearea_sphere(1), 4 * math.pi)
AssertionError: 77.8802336483881 != 12.566370614359172 within 7 places (65.31386303402893 difference)

   - [#   4] AOR datasets.GPT_4.Zero_shot2.programs.program_033: [0.00000 s] killed by test_area_1 (datasets.GPT_4.Zero_shot2.tests.test_033.TestVersion)

Traceback (most recent call last):
  File "C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.\datasets\GPT_4\Zero_shot2\tests\test_033.py", line 6, in test_area_1
    self.assertEqual(surfacearea_sphere(0), 0.0)
  File "datasets.GPT_4.Zero_shot2.programs.program_033", line 3, in surfacearea_sphere
ZeroDivisionError: float division by zero

   - [#   5] AOR datasets.GPT_4.Zero_shot2.programs.program_033: [0.00000 s] killed by test_area_1 (datasets.GPT_4.Zero_shot2.tests.test_033.TestVersion)

Traceback (most recent call last):
  File "C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.\datasets\GPT_4\Zero_shot2\tests\test_033.py", line 6, in test_area_1
    self.assertEqual(surfacearea_sphere(0), 0.0)
  File "datasets.GPT_4.Zero_shot2.programs.program_033", line 3, in surfacearea_sphere
ZeroDivisionError: float divmod()

   - [#   6] AOR datasets.GPT_4.Zero_shot2.programs.program_033: [0.00000 s] killed by test_area_3 (datasets.GPT_4.Zero_shot2.tests.test_033.TestVersion)

Traceback (most recent call last):
  File "C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.\datasets\GPT_4\Zero_shot2\tests\test_033.py", line 12, in test_area_3
    self.assertAlmostEqual(surfacearea_sphere(2), 16 * math.pi)
AssertionError: 315.82734083485946 != 50.26548245743669 within 7 places (265.56185837742277 difference)

   - [#   7] AOR datasets.GPT_4.Zero_shot2.programs.program_033: [0.00000 s] killed by test_area_1 (datasets.GPT_4.Zero_shot2.tests.test_033.TestVersion)

Traceback (most recent call last):
  File "C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.\datasets\GPT_4\Zero_shot2\tests\test_033.py", line 6, in test_area_1
    self.assertEqual(surfacearea_sphere(0), 0.0)
  File "datasets.GPT_4.Zero_shot2.programs.program_033", line 3, in surfacearea_sphere
ZeroDivisionError: float division by zero

   - [#   8] AOR datasets.GPT_4.Zero_shot2.programs.program_033: [0.00000 s] killed by test_area_1 (datasets.GPT_4.Zero_shot2.tests.test_033.TestVersion)

Traceback (most recent call last):
  File "C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.\datasets\GPT_4\Zero_shot2\tests\test_033.py", line 6, in test_area_1
    self.assertEqual(surfacearea_sphere(0), 0.0)
  File "datasets.GPT_4.Zero_shot2.programs.program_033", line 3, in surfacearea_sphere
ZeroDivisionError: float divmod()

   - [#   9] AOR datasets.GPT_4.Zero_shot2.programs.program_033: [0.00000 s] killed by test_area_1 (datasets.GPT_4.Zero_shot2.tests.test_033.TestVersion)

Traceback (most recent call last):
  File "C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.\datasets\GPT_4\Zero_shot2\tests\test_033.py", line 6, in test_area_1
    self.assertEqual(surfacearea_sphere(0), 0.0)
AssertionError: 1.0 != 0.0

[*] Mutation score [0.06259 s]: 100.0%
   - all: 9
   - killed: 9 (100.0%)
   - survived: 0 (0.0%)
   - incompetent: 0 (0.0%)
   - timeout: 0 (0.0%)
HI SANDER, RUNNING MUTPY FROM: C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.venv38\lib\site-packages\mutpy\commandline.py
