[*] Start mutation process:
   - targets: datasets.GPT_4.Few_shot1.programs.program_056
   - tests: datasets.GPT_4.Few_shot1.tests.test_056
[*] 7 tests passed:
   - datasets.GPT_4.Few_shot1.tests.test_056 [0.00000 s]
[*] Start mutants generation and execution:
   - [#   1] AOR datasets.GPT_4.Few_shot1.programs.program_056: [0.00241 s] killed by test_odd_equivalent_all (datasets.GPT_4.Few_shot1.tests.test_056.TestVersion)

Traceback (most recent call last):
  File "C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.\datasets\GPT_4\Few_shot1\tests\test_056.py", line 9, in test_odd_equivalent_all
    def test_odd_equivalent_all(self): self.assertEqual(odd_Equivalent("1111", 4), 4)
AssertionError: -4 != 4

   - [#   2] COI datasets.GPT_4.Few_shot1.programs.program_056: [0.00100 s] killed by test_odd_equivalent_all (datasets.GPT_4.Few_shot1.tests.test_056.TestVersion)

Traceback (most recent call last):
  File "C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.\datasets\GPT_4\Few_shot1\tests\test_056.py", line 9, in test_odd_equivalent_all
    def test_odd_equivalent_all(self): self.assertEqual(odd_Equivalent("1111", 4), 4)
AssertionError: 0 != 4

   - [#   3] ROR datasets.GPT_4.Few_shot1.programs.program_056: [0.00032 s] killed by test_odd_equivalent_all (datasets.GPT_4.Few_shot1.tests.test_056.TestVersion)

Traceback (most recent call last):
  File "C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.\datasets\GPT_4\Few_shot1\tests\test_056.py", line 9, in test_odd_equivalent_all
    def test_odd_equivalent_all(self): self.assertEqual(odd_Equivalent("1111", 4), 4)
AssertionError: 0 != 4

[*] Mutation score [0.03777 s]: 100.0%
   - all: 3
   - killed: 3 (100.0%)
   - survived: 0 (0.0%)
   - incompetent: 0 (0.0%)
   - timeout: 0 (0.0%)
HI SANDER, RUNNING MUTPY FROM: C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.venv38\lib\site-packages\mutpy\commandline.py
