[*] Start mutation process:
   - targets: datasets.mbpp.programs.program_066
   - tests: datasets.mbpp.tests.test_066
[*] 3 tests passed:
   - datasets.mbpp.tests.test_066 [0.00000 s]
[*] Start mutants generation and execution:
   - [#   1] AOR datasets.mbpp.programs.program_066: [0.00000 s] killed by test_angle_complex_with_0_1j_expect_1_5707963267948966 (datasets.mbpp.tests.test_066.TestVersion)

Traceback (most recent call last):
  File "C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.\datasets\mbpp\tests\test_066.py", line 6, in test_angle_complex_with_0_1j_expect_1_5707963267948966
    self.assertEqual(angle_complex(0,1j), 1.5707963267948966)
AssertionError: -1.5707963267948966 != 1.5707963267948966

[*] Mutation score [0.03173 s]: 100.0%
   - all: 1
   - killed: 1 (100.0%)
   - survived: 0 (0.0%)
   - incompetent: 0 (0.0%)
   - timeout: 0 (0.0%)
HI SANDER, RUNNING MUTPY FROM: C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.venv38\lib\site-packages\mutpy\commandline.py
