[*] Start mutation process:
   - targets: datasets.mbpp.programs.program_015
   - tests: datasets.mbpp.tests.test_015
[*] 3 tests passed:
   - datasets.mbpp.tests.test_015 [0.00000 s]
[*] Start mutants generation and execution:
   - [#   1] AOR datasets.mbpp.programs.program_015: [0.00100 s] killed by test_case (datasets.mbpp.tests.test_015.TestVersion)

Traceback (most recent call last):
  File "C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.\datasets\mbpp\tests\test_015.py", line 6, in test_case
    self.assertEqual(max_difference([(3, 5), (1, 7), (10, 3), (1, 2)]), 7)
AssertionError: 13 != 7

[*] Mutation score [0.02768 s]: 100.0%
   - all: 1
   - killed: 1 (100.0%)
   - survived: 0 (0.0%)
   - incompetent: 0 (0.0%)
   - timeout: 0 (0.0%)
HI SANDER, RUNNING MUTPY FROM: C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.venv38\lib\site-packages\mutpy\commandline.py
