coverage:
  all_nodes: 0
  covered_nodes: 0
mutation_score: 100.0
mutations:
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\o3\\\
    tests\\test_007.py\", line 6, in test_duplicates_present\n    self.assertTrue(test_duplicate([1,\
    \ 2, 3, 2]))\nAssertionError: False is not true\n"
  killer: test_duplicates_present (datasets.o3.tests.test_007.TestVersion)
  module: !!python/module:datasets.o3.programs.program_007 ''
  mutations:
  - lineno: 3
    operator: ROR
  number: 1
  status: killed
  tests_run: 1
  time: 0.0010097026824951172
number_of_tests: 5
targets:
- datasets.o3.programs.program_007
tests:
- name: datasets.o3.tests.test_007
  target: null
  time: 0.0
time_stats:
  create_mutant_module: 0.0
  create_target_ast: 0.0010101795196533203
  mutate_module: 0.01853179931640625
  run_tests_with_mutant: 0.0010097026824951172
total_time: 0.02404165267944336
