[*] Start mutation process:
   - targets: datasets.GPT_4.Few_shot.programs.program_099
   - tests: datasets.GPT_4.Few_shot.tests.test_099
[*] 8 tests passed:
   - datasets.GPT_4.Few_shot.tests.test_099 [0.00000 s]
[*] Start mutants generation and execution:
   - [#   1] ASR datasets.GPT_4.Few_shot.programs.program_099: [0.00000 s] killed by test_case_1 (datasets.GPT_4.Few_shot.tests.test_099.TestVersion)

Traceback (most recent call last):
  File "C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.\datasets\GPT_4\Few_shot\tests\test_099.py", line 6, in test_case_1
    self.assertEqual(count_Set_Bits(5), 2) # Binary 101)
AssertionError: -2 != 2

   - [#   2] COI datasets.GPT_4.Few_shot.programs.program_099: [0.00000 s] killed by test_case_1 (datasets.GPT_4.Few_shot.tests.test_099.TestVersion)

Traceback (most recent call last):
  File "C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.\datasets\GPT_4\Few_shot\tests\test_099.py", line 6, in test_case_1
    self.assertEqual(count_Set_Bits(5), 2) # Binary 101)
AssertionError: 0 != 2

   - [#   3] LOR datasets.GPT_4.Few_shot.programs.program_099: [0.00000 s] killed by test_case_1 (datasets.GPT_4.Few_shot.tests.test_099.TestVersion)

Traceback (most recent call last):
  File "C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.\datasets\GPT_4\Few_shot\tests\test_099.py", line 6, in test_case_1
    self.assertEqual(count_Set_Bits(5), 2) # Binary 101)
AssertionError: 9 != 2

   - [#   4] LOR datasets.GPT_4.Few_shot.programs.program_099: [5.04168 s] timeout
[*] Mutation score [5.05731 s]: 100.0%
   - all: 4
   - killed: 3 (75.0%)
   - survived: 0 (0.0%)
   - incompetent: 0 (0.0%)
   - timeout: 1 (25.0%)
HI SANDER, RUNNING MUTPY FROM: C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.venv38\lib\site-packages\mutpy\commandline.py
