[*] Start mutation process:
   - targets: datasets.GPT_4.Few_shot2.programs.program_021
   - tests: datasets.GPT_4.Few_shot2.tests.test_021
[*] 10 tests passed:
   - datasets.GPT_4.Few_shot2.tests.test_021 [0.00000 s]
[*] Start mutants generation and execution:
   - [#   1] AOR datasets.GPT_4.Few_shot2.programs.program_021: [0.00102 s] killed by test_is_sublist_false_non_contiguous (datasets.GPT_4.Few_shot2.tests.test_021.TestVersion)

Traceback (most recent call last):
  File "C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.\datasets\GPT_4\Few_shot2\tests\test_021.py", line 11, in test_is_sublist_false_non_contiguous
    def test_is_sublist_false_non_contiguous(self): self.assertFalse(is_sublist([1, 2, 3], [1, 3]))
AssertionError: True is not false

   - [#   2] ASR datasets.GPT_4.Few_shot2.programs.program_021: [0.00100 s] killed by test_is_sublist_duplicates (datasets.GPT_4.Few_shot2.tests.test_021.TestVersion)

Traceback (most recent call last):
  File "C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.\datasets\GPT_4\Few_shot2\tests\test_021.py", line 23, in test_is_sublist_duplicates
    def test_is_sublist_duplicates(self): self.assertTrue(is_sublist([1, 2, 2, 3], [2, 2]))
AssertionError: False is not true

   - [#   3] COI datasets.GPT_4.Few_shot2.programs.program_021: [0.00202 s] killed by test_is_sublist_empty_sublist (datasets.GPT_4.Few_shot2.tests.test_021.TestVersion)

Traceback (most recent call last):
  File "C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.\datasets\GPT_4\Few_shot2\tests\test_021.py", line 15, in test_is_sublist_empty_sublist
    def test_is_sublist_empty_sublist(self): self.assertTrue(is_sublist([1, 2, 3], []))
  File "datasets.GPT_4.Few_shot2.programs.program_021", line 11, in is_sublist
IndexError: list index out of range

   - [#   4] COI datasets.GPT_4.Few_shot2.programs.program_021: [0.00100 s] killed by test_is_sublist_false_non_contiguous (datasets.GPT_4.Few_shot2.tests.test_021.TestVersion)

Traceback (most recent call last):
  File "C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.\datasets\GPT_4\Few_shot2\tests\test_021.py", line 11, in test_is_sublist_false_non_contiguous
    def test_is_sublist_false_non_contiguous(self): self.assertFalse(is_sublist([1, 2, 3], [1, 3]))
AssertionError: True is not false

   - [#   5] COI datasets.GPT_4.Few_shot2.programs.program_021: [0.00129 s] killed by test_is_sublist_duplicates (datasets.GPT_4.Few_shot2.tests.test_021.TestVersion)

Traceback (most recent call last):
  File "C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.\datasets\GPT_4\Few_shot2\tests\test_021.py", line 23, in test_is_sublist_duplicates
    def test_is_sublist_duplicates(self): self.assertTrue(is_sublist([1, 2, 2, 3], [2, 2]))
AssertionError: False is not true

   - [#   6] COI datasets.GPT_4.Few_shot2.programs.program_021: [0.00110 s] killed by test_is_sublist_duplicates (datasets.GPT_4.Few_shot2.tests.test_021.TestVersion)

Traceback (most recent call last):
  File "C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.\datasets\GPT_4\Few_shot2\tests\test_021.py", line 23, in test_is_sublist_duplicates
    def test_is_sublist_duplicates(self): self.assertTrue(is_sublist([1, 2, 2, 3], [2, 2]))
  File "datasets.GPT_4.Few_shot2.programs.program_021", line 13, in is_sublist
IndexError: list index out of range

   - [#   7] COI datasets.GPT_4.Few_shot2.programs.program_021: [5.04637 s] timeout
   - [#   8] COI datasets.GPT_4.Few_shot2.programs.program_021: [0.00000 s] killed by test_is_sublist_false_non_contiguous (datasets.GPT_4.Few_shot2.tests.test_021.TestVersion)

Traceback (most recent call last):
  File "C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.\datasets\GPT_4\Few_shot2\tests\test_021.py", line 11, in test_is_sublist_false_non_contiguous
    def test_is_sublist_false_non_contiguous(self): self.assertFalse(is_sublist([1, 2, 3], [1, 3]))
AssertionError: True is not false

   - [#   9] LCR datasets.GPT_4.Few_shot2.programs.program_021: [0.00000 s] killed by test_is_sublist_duplicates (datasets.GPT_4.Few_shot2.tests.test_021.TestVersion)

Traceback (most recent call last):
  File "C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.\datasets\GPT_4\Few_shot2\tests\test_021.py", line 23, in test_is_sublist_duplicates
    def test_is_sublist_duplicates(self): self.assertTrue(is_sublist([1, 2, 2, 3], [2, 2]))
  File "datasets.GPT_4.Few_shot2.programs.program_021", line 13, in is_sublist
IndexError: list index out of range

   - [#  10] ROR datasets.GPT_4.Few_shot2.programs.program_021: [0.00000 s] killed by test_is_sublist_empty_sublist (datasets.GPT_4.Few_shot2.tests.test_021.TestVersion)

Traceback (most recent call last):
  File "C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.\datasets\GPT_4\Few_shot2\tests\test_021.py", line 15, in test_is_sublist_empty_sublist
    def test_is_sublist_empty_sublist(self): self.assertTrue(is_sublist([1, 2, 3], []))
  File "datasets.GPT_4.Few_shot2.programs.program_021", line 11, in is_sublist
IndexError: list index out of range

   - [#  11] ROR datasets.GPT_4.Few_shot2.programs.program_021: [0.00000 s] killed by test_is_sublist_false_non_contiguous (datasets.GPT_4.Few_shot2.tests.test_021.TestVersion)

Traceback (most recent call last):
  File "C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.\datasets\GPT_4\Few_shot2\tests\test_021.py", line 11, in test_is_sublist_false_non_contiguous
    def test_is_sublist_false_non_contiguous(self): self.assertFalse(is_sublist([1, 2, 3], [1, 3]))
AssertionError: True is not false

   - [#  12] ROR datasets.GPT_4.Few_shot2.programs.program_021: [0.00000 s] killed by test_is_sublist_duplicates (datasets.GPT_4.Few_shot2.tests.test_021.TestVersion)

Traceback (most recent call last):
  File "C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.\datasets\GPT_4\Few_shot2\tests\test_021.py", line 23, in test_is_sublist_duplicates
    def test_is_sublist_duplicates(self): self.assertTrue(is_sublist([1, 2, 2, 3], [2, 2]))
AssertionError: False is not true

   - [#  13] ROR datasets.GPT_4.Few_shot2.programs.program_021: [0.01563 s] survived
   - [#  14] ROR datasets.GPT_4.Few_shot2.programs.program_021: [0.00000 s] killed by test_is_sublist_duplicates (datasets.GPT_4.Few_shot2.tests.test_021.TestVersion)

Traceback (most recent call last):
  File "C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.\datasets\GPT_4\Few_shot2\tests\test_021.py", line 23, in test_is_sublist_duplicates
    def test_is_sublist_duplicates(self): self.assertTrue(is_sublist([1, 2, 2, 3], [2, 2]))
  File "datasets.GPT_4.Few_shot2.programs.program_021", line 13, in is_sublist
IndexError: list index out of range

   - [#  15] ROR datasets.GPT_4.Few_shot2.programs.program_021: [0.00000 s] killed by test_is_sublist_duplicates (datasets.GPT_4.Few_shot2.tests.test_021.TestVersion)

Traceback (most recent call last):
  File "C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.\datasets\GPT_4\Few_shot2\tests\test_021.py", line 23, in test_is_sublist_duplicates
    def test_is_sublist_duplicates(self): self.assertTrue(is_sublist([1, 2, 2, 3], [2, 2]))
AssertionError: False is not true

   - [#  16] ROR datasets.GPT_4.Few_shot2.programs.program_021: [0.00000 s] killed by test_is_sublist_duplicates (datasets.GPT_4.Few_shot2.tests.test_021.TestVersion)

Traceback (most recent call last):
  File "C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.\datasets\GPT_4\Few_shot2\tests\test_021.py", line 23, in test_is_sublist_duplicates
    def test_is_sublist_duplicates(self): self.assertTrue(is_sublist([1, 2, 2, 3], [2, 2]))
  File "datasets.GPT_4.Few_shot2.programs.program_021", line 13, in is_sublist
IndexError: list index out of range

   - [#  17] ROR datasets.GPT_4.Few_shot2.programs.program_021: [0.00000 s] killed by test_is_sublist_false_non_contiguous (datasets.GPT_4.Few_shot2.tests.test_021.TestVersion)

Traceback (most recent call last):
  File "C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.\datasets\GPT_4\Few_shot2\tests\test_021.py", line 11, in test_is_sublist_false_non_contiguous
    def test_is_sublist_false_non_contiguous(self): self.assertFalse(is_sublist([1, 2, 3], [1, 3]))
AssertionError: True is not false

   - [#  18] ROR datasets.GPT_4.Few_shot2.programs.program_021: [0.00000 s] killed by test_is_sublist_false_non_contiguous (datasets.GPT_4.Few_shot2.tests.test_021.TestVersion)

Traceback (most recent call last):
  File "C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.\datasets\GPT_4\Few_shot2\tests\test_021.py", line 11, in test_is_sublist_false_non_contiguous
    def test_is_sublist_false_non_contiguous(self): self.assertFalse(is_sublist([1, 2, 3], [1, 3]))
AssertionError: True is not false

[*] Mutation score [5.18609 s]: 94.4%
   - all: 18
   - killed: 16 (88.9%)
   - survived: 1 (5.6%)
   - incompetent: 0 (0.0%)
   - timeout: 1 (5.6%)
HI SANDER, RUNNING MUTPY FROM: C:\Users\skaspers\OneDrive - Capgemini\Documents\Prompted Testsuite Analysis\.venv38\lib\site-packages\mutpy\commandline.py
