coverage:
  all_nodes: 0
  covered_nodes: 0
mutation_score: 100.0
mutations:
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Chain_of_thought1\\tests\\test_096.py\", line 15, in test_adjacent_std\n    def\
    \ test_adjacent_std(self): self.assertEqual(count_occurance('stdstd'), 2)\n  File\
    \ \"datasets.GPT_4.Chain_of_thought1.programs.program_096\", line 4, in count_occurance\n\
    IndexError: string index out of range\n"
  killer: test_adjacent_std (datasets.GPT_4.Chain_of_thought1.tests.test_096.TestVersion)
  module: &id001 !!python/module:datasets.GPT_4.Chain_of_thought1.programs.program_096 ''
  mutations:
  - lineno: 3
    operator: AOR
  number: 1
  status: killed
  tests_run: 1
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Chain_of_thought1\\tests\\test_096.py\", line 15, in test_adjacent_std\n    def\
    \ test_adjacent_std(self): self.assertEqual(count_occurance('stdstd'), 2)\nAssertionError:\
    \ 0 != 2\n"
  killer: test_adjacent_std (datasets.GPT_4.Chain_of_thought1.tests.test_096.TestVersion)
  module: *id001
  mutations:
  - lineno: 4
    operator: AOR
  number: 2
  status: killed
  tests_run: 1
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Chain_of_thought1\\tests\\test_096.py\", line 15, in test_adjacent_std\n    def\
    \ test_adjacent_std(self): self.assertEqual(count_occurance('stdstd'), 2)\nAssertionError:\
    \ 0 != 2\n"
  killer: test_adjacent_std (datasets.GPT_4.Chain_of_thought1.tests.test_096.TestVersion)
  module: *id001
  mutations:
  - lineno: 4
    operator: AOR
  number: 3
  status: killed
  tests_run: 1
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Chain_of_thought1\\tests\\test_096.py\", line 15, in test_adjacent_std\n    def\
    \ test_adjacent_std(self): self.assertEqual(count_occurance('stdstd'), 2)\nAssertionError:\
    \ -2 != 2\n"
  killer: test_adjacent_std (datasets.GPT_4.Chain_of_thought1.tests.test_096.TestVersion)
  module: *id001
  mutations:
  - lineno: 5
    operator: AOR
  number: 4
  status: killed
  tests_run: 1
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Chain_of_thought1\\tests\\test_096.py\", line 21, in test_case_sensitivity\n \
    \   def test_case_sensitivity(self): self.assertEqual(count_occurance('STD'),\
    \ 0)\nAssertionError: 1 != 0\n"
  killer: test_case_sensitivity (datasets.GPT_4.Chain_of_thought1.tests.test_096.TestVersion)
  module: *id001
  mutations:
  - lineno: 4
    operator: COI
  number: 5
  status: killed
  tests_run: 2
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Chain_of_thought1\\tests\\test_096.py\", line 13, in test_no_occurrence\n    def\
    \ test_no_occurrence(self): self.assertEqual(count_occurance('abcdefg'), 0)\n\
    AssertionError: 1 != 0\n"
  killer: test_no_occurrence (datasets.GPT_4.Chain_of_thought1.tests.test_096.TestVersion)
  module: *id001
  mutations:
  - lineno: 4
    operator: LCR
  number: 6
  status: killed
  tests_run: 7
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Chain_of_thought1\\tests\\test_096.py\", line 15, in test_adjacent_std\n    def\
    \ test_adjacent_std(self): self.assertEqual(count_occurance('stdstd'), 2)\nAssertionError:\
    \ 0 != 2\n"
  killer: test_adjacent_std (datasets.GPT_4.Chain_of_thought1.tests.test_096.TestVersion)
  module: *id001
  mutations:
  - lineno: 4
    operator: ROR
  number: 7
  status: killed
  tests_run: 1
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Chain_of_thought1\\tests\\test_096.py\", line 15, in test_adjacent_std\n    def\
    \ test_adjacent_std(self): self.assertEqual(count_occurance('stdstd'), 2)\nAssertionError:\
    \ 0 != 2\n"
  killer: test_adjacent_std (datasets.GPT_4.Chain_of_thought1.tests.test_096.TestVersion)
  module: *id001
  mutations:
  - lineno: 4
    operator: ROR
  number: 8
  status: killed
  tests_run: 1
  time: 0.0
- exception_traceback: "Traceback (most recent call last):\n  File \"C:\\Users\\skaspers\\\
    OneDrive - Capgemini\\Documents\\Prompted Testsuite Analysis\\.\\datasets\\GPT_4\\\
    Chain_of_thought1\\tests\\test_096.py\", line 15, in test_adjacent_std\n    def\
    \ test_adjacent_std(self): self.assertEqual(count_occurance('stdstd'), 2)\nAssertionError:\
    \ 0 != 2\n"
  killer: test_adjacent_std (datasets.GPT_4.Chain_of_thought1.tests.test_096.TestVersion)
  module: *id001
  mutations:
  - lineno: 4
    operator: ROR
  number: 9
  status: killed
  tests_run: 1
  time: 0.0
number_of_tests: 12
targets:
- datasets.GPT_4.Chain_of_thought1.programs.program_096
tests:
- name: datasets.GPT_4.Chain_of_thought1.tests.test_096
  target: null
  time: 0.0
time_stats:
  create_mutant_module: 0.0
  create_target_ast: 0.0
  mutate_module: 0.06308650970458984
  run_tests_with_mutant: 0.0
total_time: 0.07965207099914551
